Implemented strategic patching and added unit test (issue #181)
siderolabs/cluster-api-bootstrap-provider-talos pull request #189
Opened 2024-02-14 08:52 UTC by ksawio97

2024-02-18 19:01 UTC, yoctozepto requested changes
Please also fix the issues with the commit message pointed out by CI.

2024-02-18 19:01 UTC, yoctozepto commented on api/v1alpha3/talosconfig_types.go
> +	StrategicPatch StrategicPatch  `json:"strategicPatch,omitempty"`
1) It's a "strategic *merge*" patch so the current wording is wrong. I think we could get away with calling it ConfigPatch (the singular) and clarifying further in the docs.
2) It would be more appropriate to make it a `string` and convert to `[]bytes` only where necessary.

2024-02-18 19:01 UTC, yoctozepto commented on api/v1alpha3/types.go
> +type StrategicPatch []byte
This would get dropped.

2024-02-18 19:01 UTC, yoctozepto commented on config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigs.yaml
> +                format: byte
This would get dropped.

2024-02-18 19:01 UTC, yoctozepto commented on config/crd/bases/bootstrap.cluster.x-k8s.io_talosconfigtemplates.yaml
> +                        format: byte
This would get dropped.

2024-02-18 19:01 UTC, yoctozepto commented on controllers/talosconfig_controller.go
> +	// Handle strategic patches
Again, "strategic *merge*".

2024-02-18 19:01 UTC, yoctozepto commented on controllers/talosconfig_controller.go
> +		// try reading strategic patch
Ditto.

2024-02-18 19:01 UTC, yoctozepto commented on controllers/talosconfig_controller.go
> +		// try reading strategic patch
Also, this and below comments are not very useful because they rephrase the already-short-and-understandable code below them. Let's remove all.

2024-02-18 19:01 UTC, yoctozepto commented on internal/integration/integration_test.go
> +	"fmt"
Let's not import.

2024-02-18 19:01 UTC, yoctozepto commented on internal/integration/integration_test.go
> +			fmt.Sprintf("machine:\n network:\n  hostname: %s\n time:\n  servers: [%s]", expectedHostName, strings.Join(expectedServers, ",")),
As this is a test case, it would be best to be explicit about how this YAML chunk looks like. Best use a multiline string to write down this YAML snippet.

2024-02-18 19:01 UTC, yoctozepto commented on internal/integration/integration_test.go
> +		strategicPatch := bootstrapv1alpha3.StrategicPatch(
By this point you already know it - "strategic *merge*" patch. ;-)

2024-02-18 19:03 UTC, yoctozepto commented
@smira This is our take at issue #181 that I discussed with you a while ago. I think it will be good to go once my review comments are fixed. Please let us know if there are any further steps.

2024-02-20 13:44 UTC, yoctozepto commented
Almost there - you need to fix the small typo in the commit message and add the sign-off (as `git commit -s` does) to it.

2024-02-20 13:47 UTC, yoctozepto commented
BTW, you can update also the PR title and details as they are off now (they initially copied from the commits originally proposed for the PR).

2024-02-21 07:58 UTC, yoctozepto approved these changes
LGTM, thank you!

2024-04-17 12:28 UTC, smira commented
/ok-to-test

2024-04-17 12:29 UTC, smira approved these changes
thanks for your PR, I did some changes, but mostly stays same

2024-04-17 12:31 UTC, frezbo approved these changes

2024-04-17 13:08 UTC, smira commented
/m

2024-04-17 13:08 UTC, merged